
" Theme and Number

set number

" configure expanding of tabs for various file types
au BufRead,BufNewFile *.py set expandtab
au BufRead,BufNewFile *.c set noexpandtab
au BufRead,BufNewFile *.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab

" --------------------------------------------------------------------------------
" configure editor with tabs and nice stuff...
" --------------------------------------------------------------------------------

set expandtab           " enter spaces when tab is pressed
set textwidth=120       " break lines when line length increases
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line
set whichwrap+=<,>,[,]  " make the left and right arrow keys change line

" make backspaces more powerfull
set backspace=indent,eol,start

set ruler               " show line and column number
syntax on               " syntax highlighting
set showcmd             " show (partial) command in status line

" Ctrl + Shift + Up / Down To Move Line Up or Down
noremap <c-s-up> :call feedkeys( line('.')==1 ? '' : 'ddkP' )<CR>
noremap <c-s-down> ddp
nmap <C-d> mzyyp`z

" have Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Plugins
" install vim package manager vim-plug
" https://github.com/junegunn/vim-plug.git
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'tomasr/molokai'
Plug 'cocopon/iceberg.vim'
Plug 'wolf-dog/nighted.vim'
Plug 'https://github.com/endel/vim-github-colorscheme.git'
Plug 'fcpg/vim-fahrenheit'
Plug 'morhetz/gruvbox'
Plug 'sjl/badwolf'

call plug#end()

" theme mode
set background=dark

"colorscheme molokai
"colorscheme github
"colorscheme gruvbox
"colorscheme badwolf
colorscheme fahrenheit
